USE [master]
GO
/****** Object:  Database [Hotel_DB]    Script Date: 16.01.2018 17:05:06 ******/
CREATE DATABASE [Hotel_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hotel_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Hotel_DB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Hotel_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Hotel_DB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Hotel_DB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hotel_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Hotel_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Hotel_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Hotel_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Hotel_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Hotel_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [Hotel_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Hotel_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Hotel_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Hotel_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Hotel_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Hotel_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Hotel_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Hotel_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Hotel_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Hotel_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Hotel_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Hotel_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Hotel_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Hotel_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Hotel_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Hotel_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Hotel_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Hotel_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [Hotel_DB] SET  MULTI_USER 
GO
ALTER DATABASE [Hotel_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Hotel_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Hotel_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Hotel_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Hotel_DB]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 16.01.2018 17:05:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[IdBooking] [int] IDENTITY(1,1) NOT NULL,
	[Fristname] [nchar](10) NOT NULL,
	[Lastname] [nchar](10) NOT NULL,
	[Checkin] [date] NOT NULL,
	[Checkout] [date] NOT NULL,
	[NbPerson] [int] NOT NULL,
 CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[IdBooking] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Booking_has_Room]    Script Date: 16.01.2018 17:05:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Booking_has_Room](
	[IdBooking] [int] NOT NULL,
	[IdRoom] [int] NOT NULL,
	[Price] [money] NOT NULL,
 CONSTRAINT [PK_Booking_has_Room] PRIMARY KEY CLUSTERED 
(
	[IdBooking] ASC,
	[IdRoom] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Hotel]    Script Date: 16.01.2018 17:05:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Hotel](
	[IdHotel] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[Location] [nvarchar](50) NOT NULL,
	[Category] [int] NOT NULL,
	[HasWifi] [bit] NOT NULL,
	[HasParking] [bit] NOT NULL,
	[Phone] [varchar](20) NULL,
	[Email] [varchar](50) NULL,
	[Website] [varchar](100) NULL,
 CONSTRAINT [PK_Hotel] PRIMARY KEY CLUSTERED 
(
	[IdHotel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Picture]    Script Date: 16.01.2018 17:05:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Picture](
	[IdPicture] [int] NOT NULL,
	[Url] [nvarchar](max) NOT NULL,
	[IdRoom] [int] NOT NULL,
 CONSTRAINT [PK_Picture] PRIMARY KEY CLUSTERED 
(
	[IdPicture] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Room]    Script Date: 16.01.2018 17:05:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Room](
	[IdRoom] [int] NOT NULL,
	[Number] [int] NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[Type] [int] NOT NULL,
	[Price] [numeric](5, 2) NOT NULL,
	[HasTV] [bit] NOT NULL,
	[HasHairDryer] [bit] NOT NULL,
	[IdHotel] [int] NOT NULL,
 CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED 
(
	[IdRoom] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Booking_has_Room]  WITH CHECK ADD  CONSTRAINT [FK_Booking_has_Room_Book] FOREIGN KEY([IdBooking])
REFERENCES [dbo].[Book] ([IdBooking])
GO
ALTER TABLE [dbo].[Booking_has_Room] CHECK CONSTRAINT [FK_Booking_has_Room_Book]
GO
ALTER TABLE [dbo].[Booking_has_Room]  WITH CHECK ADD  CONSTRAINT [FK_Booking_has_Room_Room] FOREIGN KEY([IdRoom])
REFERENCES [dbo].[Room] ([IdRoom])
GO
ALTER TABLE [dbo].[Booking_has_Room] CHECK CONSTRAINT [FK_Booking_has_Room_Room]
GO
ALTER TABLE [dbo].[Picture]  WITH CHECK ADD  CONSTRAINT [FK_Picture_Room] FOREIGN KEY([IdRoom])
REFERENCES [dbo].[Room] ([IdRoom])
GO
ALTER TABLE [dbo].[Picture] CHECK CONSTRAINT [FK_Picture_Room]
GO
ALTER TABLE [dbo].[Room]  WITH CHECK ADD  CONSTRAINT [FK_Room_Hotel] FOREIGN KEY([IdHotel])
REFERENCES [dbo].[Hotel] ([IdHotel])
GO
ALTER TABLE [dbo].[Room] CHECK CONSTRAINT [FK_Room_Hotel]
GO
USE [master]
GO
ALTER DATABASE [Hotel_DB] SET  READ_WRITE 
GO
